export const allTools = [
  {
    id: "word-counter",
    title: "Word Counter",
    description: "Count words, characters, sentences and reading time instantly.",
    href: "/tools/word-counter",
    category: "Text",
    badge: "FREE",
    featured: true,
    popular: true,
    comingSoon: false,
  },
  {
    id: "character-counter",
    title: "Character Counter",
    description: "Count characters with live updates.",
    href: "/tools/character-counter",
    category: "Text",
    badge: "FREE",
    featured: true,
    popular: true,
    comingSoon: false,
  },
  {
    id: "case-converter",
    title: "Case Converter",
    description: "Convert text between uppercase, lowercase and other formats.",
    href: "/tools/case-converter",
    category: "Text",
    badge: "FREE",
    featured: false,
    popular: true,
    comingSoon: false,
  },
  {
    id: "text-to-slug",
    title: "Text to Slug",
    description: "Generate clean, SEO-friendly URL slugs instantly.",
    href: "/tools/text-to-slug",
    category: "SEO",
    badge: "FREE",
    featured: false,
    popular: true,
    comingSoon: false,
  },
  {
    id: "meta-generator",
    title: "Meta Generator",
    description: "Generate optimized SEO titles and meta descriptions.",
    href: "/tools/meta-generator",
    category: "SEO",
    badge: "FREE",
    featured: true,
    popular: true,
    comingSoon: false,
  },
  {
    id: "robots-generator",
    title: "Robots.txt Generator",
    description: "Create robots.txt files for search engines.",
    href: "/tools/robots-generator",
    category: "SEO",
    badge: "FREE",
    featured: false,
    popular: false,
    comingSoon: false,
  },
  {
    id: "sitemap-generator",
    title: "Sitemap Generator",
    description: "Generate XML sitemaps for better search indexing.",
    href: "/tools/sitemap-generator",
    category: "SEO",
    badge: "FREE",
    featured: false,
    popular: false,
    comingSoon: false,
  },
  {
    id: "json-formatter",
    title: "JSON Formatter",
    description: "Beautify, validate and format JSON instantly.",
    href: "/tools/json-formatter",
    category: "Developer",
    badge: "FREE",
    featured: true,
    popular: true,
    comingSoon: false,
  },
  {
    id: "html-minifier",
    title: "HTML Minifier",
    description: "Compress HTML code without changing its output.",
    href: "/tools/html-minifier",
    category: "Developer",
    badge: "FREE",
    featured: false,
    popular: false,
    comingSoon: false,
  },
  {
    id: "password-generator",
    title: "Password Generator",
    description: "Generate secure and random passwords instantly.",
    href: "/tools/password-generator",
    category: "Utilities",
    badge: "FREE",
    featured: true,
    popular: true,
    comingSoon: false,
  },
];