export const workspaces = [
  {
    title: "AI Workspace",
    description: "AI writing, prompts, automation & productivity.",
    href: "/ai",
    icon: "bot",
    tools: 18,
  },
  {
    title: "SEO Workspace",
    description: "Meta, Schema, Robots, Sitemap & SEO tools.",
    href: "/seo",
    icon: "search",
    tools: 15,
  },
  {
    title: "GEO Workspace",
    description: "Optimize content for AI search engines.",
    href: "/geo",
    icon: "sparkles",
    tools: 8,
  },
  {
    title: "AEO Workspace",
    description: "Answer Engine Optimization.",
    href: "/aeo",
    icon: "message-circle",
    tools: 10,
  },
  {
    title: "SMO Workspace",
    description: "Social Media Optimization.",
    href: "/smo",
    icon: "share2",
    tools: 10,
  },
  {
    title: "Developer Workspace",
    description: "Developer tools & utilities.",
    href: "/developer",
    icon: "code2",
    tools: 24,
  },
  {
    title: "Text Workspace",
    description: "Text editing & writing tools.",
    href: "/text",
    icon: "type",
    tools: 20,
  },
  {
    title: "Image Workspace",
    description: "Image optimization tools.",
    href: "/image",
    icon: "image",
    tools: 12,
  },
  {
    title: "PDF Workspace",
    description: "PDF utilities.",
    href: "/pdf",
    icon: "file-text",
    tools: 14,
  },
];