import {
  Bot,
  Search,
  Sparkles,
  Share2,
  Code2,
  Type,
  Image,
  FileText,
} from "lucide-react";

export const workspaces = [
  {
    title: "AI Workspace",
    description: "AI writing, prompts, automation & productivity.",
    href: "/ai",
    icon: Bot,
    color: "cyan",
    tools: 18,
  },
  {
    title: "SEO Workspace",
    description: "Meta, Schema, Robots, Sitemap & SEO tools.",
    href: "/seo",
    icon: Search,
    color: "emerald",
    tools: 15,
  },
  {
    title: "GEO Workspace",
    description: "Optimize content for AI search engines.",
    href: "/geo",
    icon: Sparkles,
    color: "purple",
    tools: 8,
  },
  {
    title: "SMO Workspace",
    description: "Social media optimization tools.",
    href: "/smo",
    icon: Share2,
    color: "pink",
    tools: 10,
  },
  {
    title: "Developer",
    description: "JSON, HTML, CSS, Base64 & developer tools.",
    href: "/developer",
    icon: Code2,
    color: "orange",
    tools: 24,
  },
  {
    title: "Text Tools",
    description: "Word Counter, Slug, Case Converter & more.",
    href: "/text",
    icon: Type,
    color: "blue",
    tools: 20,
  },
  {
    title: "Image Tools",
    description: "Resize, Compress, Convert & Optimize.",
    href: "/image",
    icon: Image,
    color: "rose",
    tools: 12,
  },
  {
    title: "PDF Tools",
    description: "Merge, Split, Compress & Convert PDFs.",
    href: "/pdf",
    icon: FileText,
    color: "red",
    tools: 14,
  },
];